spring.application.name=01_CHEAM_NORAKPANHA_PVH_SPRING_Homework003
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_hw3_db
spring.datasource.username=postgres
spring.datasource.password=123